//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopLaptop.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhGia
    {
        public int madanhgia { get; set; }
        public string ten { get; set; }
        public string noidung { get; set; }
        public Nullable<int> vote { get; set; }
        public Nullable<System.DateTime> ngaydanhgia { get; set; }
        public Nullable<int> malaptop { get; set; }
    
        public virtual Laptop Laptop { get; set; }
    }
}
