//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopLaptop.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class LienHe
    {
        public int malienhe { get; set; }
        public string hoten { get; set; }
        public string email { get; set; }
        public string dienthoai { get; set; }
        public string website { get; set; }
        public string noidung { get; set; }
        public Nullable<bool> trangthai { get; set; }
    }
}
