//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopLaptop.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MetaLaptop
    {
        public int mameta { get; set; }
        public string keymeta { get; set; }
        public string valuemeta { get; set; }
        public Nullable<int> malaptop { get; set; }
    
        public virtual Laptop Laptop { get; set; }
    }
}
