//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopLaptop.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuangCao
    {
        public int maqc { get; set; }
        public string tenqc { get; set; }
        public string tencongty { get; set; }
        public string hinhnen { get; set; }
        public string link { get; set; }
        public Nullable<System.DateTime> ngaybatdau { get; set; }
        public Nullable<System.DateTime> ngayhethan { get; set; }
        public bool trangthai { get; set; }
    }
}
