//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopLaptop.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TinTuc
    {
        public int matin { get; set; }
        public string tieude { get; set; }
        public string hinhnen { get; set; }
        public string tomtat { get; set; }
        public string slug { get; set; }
        public string noidung { get; set; }
        public Nullable<int> luotxem { get; set; }
        public Nullable<System.DateTime> ngaycapnhat { get; set; }
        public Nullable<bool> xuatban { get; set; }
        public Nullable<int> machude { get; set; }
    
        public virtual ChuDe ChuDe { get; set; }
    }
}
